AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This is a SAM template for lol-api which is a Serverless API for
  composing and managing Covid Data.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  ExecEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - stage
      - prod
    Default: prod
  CovidDashboardName:
    Type: String
    Default: country-stats

Resources:
  CovidFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: flask_api/
      Handler: app.app
      Runtime: python3.8
      Environment:
        Variables:
          REGION_NAME: !Ref AWS::Region
          EXEC_ENV: !Ref ExecEnv
          DB_URL: postgresql://etl:etl@3.128.133.211:5432/dw
      Events:
        FetchCountries:
          Type: Api
          Properties:
            Path: /countries/
            Method: get
        FetchCountry:
          Type: Api
          Properties:
            Path: /countries/{country_id}/
            Method: get
        FetchStates:
          Type: Api
          Properties:
            Path: /states/
            Method: get
        FetchState:
          Type: Api
          Properties:
            Path: /states/{state_id}/
            Method: get
        FetchCities:
          Type: Api
          Properties:
            Path: /cities/
            Method: get
        FetchCity:
          Type: Api
          Properties:
            Path: /cities/{city_id}/
            Method: get


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CovidDashboardAPI:
    Description: "API Gateway endpoint URL for Prod stage for Covid Data function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lists"
  CovidDashboardFunction:
    Description: "Covid Data Lambda Function ARN"
    Value: !GetAtt CovidDashboardFunction.Arn
  CovidDashboardFunctionIamRole:
    Description: "Implicit IAM Role created for Covid Data function"
    Value: !GetAtt CovidDashboardFunctionRole.Arn